import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GraphQLClient,gql} from 'graphql-request';
import BlogCard from './components/Blogcard';

const graphcms = new GraphQLClient('https://api-us-west-2.hygraph.com/v2/cl95r8dmd6dnf01ukeleo4izk/master');

const QUERY = gql`
query Posts{
  posts{
    title,
    slug,
    coverPhoto{
      url
    }
    content{
      html
    }
  }
}
`;
export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return{
    props: {
      posts,
    },
    revalidate: 10,
  };
}
export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       {posts.map((post) => (
       <BlogCard 
          title={post.title} 
          coverPhoto = {post.coverPhoto} 
          key = {post.id}
          slug = {post.slug}
           />))}
      </main>

      
    </div>
  )
}
